# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='ContractorRep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=35)),
                ('officenumber', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=55)),
                ('company', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=220)),
                ('salesRep', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=220)),
                ('daily', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weekly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monthly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('additionalCost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('addCostDescript', models.CharField(max_length=200)),
                ('distributor', models.CharField(max_length=220)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaborRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=20)),
                ('local', models.CharField(max_length=2)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fringes', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fica', models.DecimalField(decimal_places=2, max_digits=8)),
                ('futa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sui', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('liability', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disability', models.DecimalField(decimal_places=2, max_digits=8)),
                ('roomboard', models.DecimalField(decimal_places=2, max_digits=8)),
                ('travel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tools', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=220)),
                ('productRep', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=220)),
                ('materialType', models.CharField(choices=[('WP', 'Waterproofing'), ('DP', 'Dampproofing'), ('CK', 'Caulking'), ('SL', 'Sealar'), ('TC', 'Traffic Coating'), ('EJ', 'Expansion Joint'), ('FS', 'Fire Stopping'), ('AB', 'Air Barrier'), ('VB', 'Vapor Barrier'), ('OT', 'Other')], default='OT', max_length=2)),
                ('subCategory', models.CharField(choices=[('FAA', 'Fluid-Applied Air Barrier'), ('SAB', 'Sheet Membrane Air Barrier'), ('ABA', 'Air Barrier Accessory'), ('ABO', 'Air Barrier Other'), ('SWP', 'Sheet Waterproofing'), ('FAW', 'Fluid-Applied Waterproofing'), ('DRM', 'Drain Mat'), ('PRB', 'Protection Board'), ('WPA', 'Waterproofing Accessory'), ('WPO', 'Waterproofing Other'), ('SIL', 'Silicone Sealant'), ('LAX', 'Latex Sealant'), ('URE', 'Urethane Sealant'), ('SAN', 'Sanitary Sealant'), ('SAC', 'Sealant Accessory'), ('SEO', 'Sealant Other'), ('OT', 'Other')], default='OT', max_length=55)),
                ('footagePerUnit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costPerUnit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('manufacturer', models.CharField(max_length=50)),
                ('dataSheetURL', models.CharField(max_length=200)),
                ('sdsURL', models.CharField(max_length=200)),
                ('distributor', models.CharField(max_length=220)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('footageType', models.CharField(choices=[('SF', 'Square Footage'), ('LF', 'Lineal Footage'), ('CT', 'Count')], default='SF', max_length=2)),
                ('scope', models.CharField(choices=[('WP', 'Waterproofing'), ('DP', 'Dampproofing'), ('CK', 'Caulking'), ('SL', 'Sealer'), ('TC', 'Traffic Coating'), ('EJ', 'Expansion Joint'), ('FS', 'Fire Stopping'), ('AB', 'Air Barrier'), ('VB', 'Vapor Barrier'), ('OT', 'Other')], default='OT', max_length=2)),
                ('productionTime', models.CharField(choices=[('MD', 'Man Day'), ('MH', 'Man Hour'), ('2D', 'Two Man Crew - 1 Day'), ('3D', 'Three Man Crew - 1 Day'), ('4D', 'Four Man Crew - 1 Day')], default='MH', max_length=2)),
                ('production', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductRep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=35)),
                ('officenumber', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=35)),
                ('officenumber', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=55)),
            ],
        ),
    ]
